# Generated by Django 4.2.5 on 2023-10-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(max_length=100)),
                ('col_description', models.CharField(max_length=500)),
                ('col_cover', models.CharField(default='img', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=100)),
                ('p_type', models.CharField(default='article', max_length=100)),
                ('p_artist', models.CharField(max_length=100)),
                ('p_year', models.IntegerField()),
                ('p_cover', models.CharField(default='img', max_length=1000)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.collections')),
            ],
        ),
    ]
